version: '2'
services:
  moodledata:
    image: prodest/moodle-docker:moodledata
  mysql:
    image: prodest/moodle-docker:mariadb
    depends_on:
      - moodledata
    volumes_from: 
      - moodledata
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis
  webserver:
    image: prodest/moodle-docker:php-fpm
    depends_on:
      - mysql
      - redis
      - moodledata
    links:
      - mysql:mysql
      - redis:redis
    volumes_from: 
      - moodledata
    environment:
      - CI_ENV=development
      - TZ=America/Sao_Paulo
    restart: always
