version: '2'
services:
  mysql:
    image: prodest/moodle-docker:mariadb
    volumes: 
      - ./moodledata/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=moodle
    ports:
      - 3306:3306
  redis:
    image: redis
  webserver:
    image: prodest/moodle-docker:php-fpm
    depends_on:
      - mysql
      - redis
    links:
      - mysql:mysql
      - redis:redis
    volumes: 
      - ./moodledata/moodle:/var/www/src/public
      - ./moodledata/moodledata:/var/www/src/moodledata
    environment:
      - CI_ENV=development
      - TZ=America/Sao_Paulo
    restart: always
    ports: 
      - 80:80
